const express = require('express');
const app = express();
// const cors = require('cors');
// app.use(cors({origin: '*'}));
const appRouter = require('./routes');
const port = 3000;
const host = '127.0.0.1';
app.use('/', appRouter);
app.listen(port, host);
console.log('Node server running on port 3000 ...');